### ISSUE TITLE
Architecture du programme Python

### ISSUE THREAD

**Issue by leboulec** [PolyCoro/CoroMail#7]
Nous devons nous mettre d'accord sur l'architecture du programme Python.

Nous devons faire un diagramme des classes que l'on utilisera.

**Comment by V1nc3ntL** [comment]
Le diagramme de classe actuellement pris en compte :
![Diagramme de classe - Serveur](https://user-images.githubusercontent.com/47301990/148738969-8402701d-f4d3-48eb-a2a6-df42908a32e1.png)
